server:
  servlet:
    context-path: /kcbs

spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create
      default_batch_fetch_size: 500
    properties:
      hibernate:
        format_sql: true

  security:
    user:
      password: 1

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
